-- ============================================================
-- Nutrio Food Database Seed
-- Paste this into Supabase Dashboard → SQL Editor → Run
-- ============================================================
-- Make sure your foods table has these columns:
--   id        BIGSERIAL PRIMARY KEY  (or UUID with gen_random_uuid())
--   name      TEXT NOT NULL
--   calories  INTEGER NOT NULL
--   category  TEXT NOT NULL
--   added_by  UUID REFERENCES auth.users(id) DEFAULT NULL
-- ============================================================

INSERT INTO foods (name, calories, category) VALUES

-- ============================================================
-- FRUITS
-- ============================================================
('Apple (1 medium)', 95, 'fruits'),
('Banana (1 medium)', 105, 'fruits'),
('Orange (1 medium)', 62, 'fruits'),
('Grapes (1 cup)', 104, 'fruits'),
('Strawberries (1 cup)', 49, 'fruits'),
('Blueberries (1 cup)', 84, 'fruits'),
('Watermelon (1 cup diced)', 46, 'fruits'),
('Pineapple (1 cup chunks)', 82, 'fruits'),
('Mango (1 cup)', 99, 'fruits'),
('Peach (1 medium)', 58, 'fruits'),
('Pear (1 medium)', 101, 'fruits'),
('Kiwi (1 medium)', 42, 'fruits'),
('Avocado (1/2 medium)', 120, 'fruits'),
('Cherries (1 cup)', 87, 'fruits'),
('Raspberries (1 cup)', 64, 'fruits'),
('Blackberries (1 cup)', 62, 'fruits'),
('Cantaloupe (1 cup)', 54, 'fruits'),
('Grapefruit (1/2 medium)', 52, 'fruits'),
('Lemon (1 medium)', 17, 'fruits'),
('Lime (1 medium)', 20, 'fruits'),
('Pomegranate (1/2 cup seeds)', 83, 'fruits'),
('Apricot (2 medium)', 34, 'fruits'),
('Plum (1 medium)', 30, 'fruits'),
('Nectarine (1 medium)', 62, 'fruits'),
('Fig (2 medium)', 74, 'fruits'),
('Coconut meat (1 oz)', 99, 'fruits'),

-- ============================================================
-- VEGETABLES
-- ============================================================
('Broccoli (1 cup raw)', 31, 'vegetables'),
('Carrot (1 medium)', 25, 'vegetables'),
('Spinach (1 cup raw)', 7, 'vegetables'),
('Tomato (1 medium)', 22, 'vegetables'),
('Grape tomatoes (1 cup)', 30, 'vegetables'),
('Bell pepper, red (1 medium)', 37, 'vegetables'),
('Bell pepper, green (1 medium)', 24, 'vegetables'),
('Cucumber (1 cup sliced)', 16, 'vegetables'),
('Romaine lettuce (1 cup)', 8, 'vegetables'),
('Celery (1 stalk)', 6, 'vegetables'),
('Onion (1 medium)', 44, 'vegetables'),
('Garlic (1 clove)', 4, 'vegetables'),
('Corn on the cob (1 ear)', 77, 'vegetables'),
('Green beans, canned, drained (1 cup)', 27, 'vegetables'),
('Sweet potato (1 medium baked)', 103, 'vegetables'),
('Baked potato (1 medium)', 161, 'vegetables'),
('Cauliflower (1 cup raw)', 25, 'vegetables'),
('Brussels sprouts (1 cup)', 38, 'vegetables'),
('Asparagus (1 cup)', 27, 'vegetables'),
('Kale (1 cup raw)', 34, 'vegetables'),
('Zucchini (1 cup sliced)', 20, 'vegetables'),
('Mushrooms (1 cup sliced)', 15, 'vegetables'),
('Beets (1 cup cooked)', 74, 'vegetables'),
('Artichoke (1 medium)', 60, 'vegetables'),
('Eggplant (1 cup cooked)', 35, 'vegetables'),
('Cabbage (1 cup raw)', 22, 'vegetables'),
('Bok choy (1 cup raw)', 9, 'vegetables'),
('Arugula (1 cup)', 5, 'vegetables'),
('Peas, green (1/2 cup)', 59, 'vegetables'),
('Butternut squash (1 cup cooked)', 82, 'vegetables'),
('Radish (1 cup sliced)', 19, 'vegetables'),

-- ============================================================
-- GRAINS & BREADS
-- ============================================================
('White rice (1 cup cooked)', 206, 'grains'),
('Brown rice (1 cup cooked)', 216, 'grains'),
('Oatmeal (1 cup cooked)', 158, 'grains'),
('White bread (1 slice)', 79, 'grains'),
('Whole wheat bread (1 slice)', 81, 'grains'),
('Bagel, plain (1 medium)', 245, 'grains'),
('Pasta, plain (1 cup cooked)', 220, 'grains'),
('Quinoa (1 cup cooked)', 222, 'grains'),
('Granola (1/2 cup)', 209, 'grains'),
('Corn flakes (1 cup)', 101, 'grains'),
('Cheerios (1 cup)', 100, 'grains'),
('Pancake (1 medium)', 86, 'grains'),
('Waffle (1 medium)', 218, 'grains'),
('English muffin (1 whole)', 132, 'grains'),
('Croissant (1 medium)', 231, 'grains'),
('Flour tortilla (1 medium)', 146, 'grains'),
('Corn tortilla (1 medium)', 52, 'grains'),
('Crackers, salted (5 pieces)', 75, 'grains'),
('Granola bar (1 bar)', 195, 'grains'),
('Pita bread (1 whole, 6 inch)', 165, 'grains'),
('Sourdough bread (1 slice)', 93, 'grains'),
('Rye bread (1 slice)', 83, 'grains'),
('Naan bread (1 piece)', 262, 'grains'),
('Couscous (1 cup cooked)', 176, 'grains'),
('Muffin, blueberry (1 medium)', 313, 'grains'),
('Biscuit (1 medium)', 212, 'grains'),
('Dinner roll (1 roll)', 84, 'grains'),
('Ramen noodles, cooked (1 cup)', 190, 'grains'),
('Instant oatmeal packet (1 packet)', 160, 'grains'),

-- ============================================================
-- PROTEINS (MEAT, POULTRY, FISH, EGGS)
-- ============================================================
('Chicken breast, grilled (3 oz)', 140, 'proteins'),
('Chicken thigh, baked (3 oz)', 179, 'proteins'),
('Chicken drumstick, baked (3 oz)', 146, 'proteins'),
('Ground beef 85% lean (3 oz cooked)', 218, 'proteins'),
('Sirloin steak (3 oz cooked)', 180, 'proteins'),
('Ribeye steak (3 oz cooked)', 235, 'proteins'),
('Salmon, baked (3 oz)', 177, 'proteins'),
('Tuna, canned in water (3 oz)', 109, 'proteins'),
('Shrimp, cooked (3 oz)', 84, 'proteins'),
('Tilapia, baked (3 oz)', 109, 'proteins'),
('Turkey breast, roasted (3 oz)', 135, 'proteins'),
('Pork chop, baked (3 oz)', 187, 'proteins'),
('Bacon (2 slices cooked)', 87, 'proteins'),
('Sausage link (1 pork link)', 85, 'proteins'),
('Beef frankfurter (1 frank, 1.5 oz)', 150, 'proteins'),
('Egg, whole (1 large)', 72, 'proteins'),
('Egg white (1 large)', 17, 'proteins'),
('Scrambled eggs (2 large eggs)', 182, 'proteins'),
('Ham, deli sliced (3 oz)', 138, 'proteins'),
('Canned sardines (3 oz)', 177, 'proteins'),
('Canned salmon (3 oz)', 130, 'proteins'),
('Cod, baked (3 oz)', 89, 'proteins'),
('Crab meat (3 oz)', 82, 'proteins'),
('Lobster (3 oz cooked)', 83, 'proteins'),
('Lamb chop (3 oz cooked)', 200, 'proteins'),
('Ground turkey (3 oz cooked)', 170, 'proteins'),
('Pepperoni (1 oz, ~14 slices)', 130, 'proteins'),
('Rotisserie chicken breast (3 oz)', 170, 'proteins'),
('Halibut, baked (3 oz)', 94, 'proteins'),

-- ============================================================
-- DAIRY
-- ============================================================
('Whole milk (1 cup)', 149, 'dairy'),
('2% milk (1 cup)', 122, 'dairy'),
('Skim milk (1 cup)', 83, 'dairy'),
('Cheddar cheese (1 oz)', 113, 'dairy'),
('Mozzarella cheese (1 oz)', 85, 'dairy'),
('Swiss cheese (1 oz)', 108, 'dairy'),
('Parmesan cheese, grated (1 tbsp)', 22, 'dairy'),
('Greek yogurt, plain nonfat (6 oz)', 100, 'dairy'),
('Regular yogurt, plain (6 oz)', 107, 'dairy'),
('Butter (1 tbsp)', 102, 'dairy'),
('Cream cheese (1 tbsp)', 51, 'dairy'),
('Sour cream (2 tbsp)', 60, 'dairy'),
('Heavy cream (1 tbsp)', 51, 'dairy'),
('Ice cream, vanilla (1/2 cup)', 137, 'dairy'),
('Cottage cheese, low-fat (1/2 cup)', 81, 'dairy'),
('American cheese slice (1 slice)', 65, 'dairy'),
('Brie cheese (1 oz)', 95, 'dairy'),
('Chocolate milk, whole (1 cup)', 208, 'dairy'),
('Almond milk, unsweetened (1 cup)', 39, 'dairy'),
('Oat milk (1 cup)', 120, 'dairy'),
('Half and half (1 tbsp)', 20, 'dairy'),
('Provolone cheese (1 oz)', 98, 'dairy'),
('Feta cheese (1 oz)', 74, 'dairy'),
('Cream cheese, full fat (1 tbsp)', 51, 'dairy'),
('Whipped cream (2 tbsp)', 15, 'dairy'),

-- ============================================================
-- LEGUMES & PLANT PROTEINS
-- ============================================================
('Hummus, commercial (2 tbsp)', 78, 'legumes'),
('Black beans (1/2 cup cooked)', 114, 'legumes'),
('Kidney beans (1/2 cup cooked)', 112, 'legumes'),
('Chickpeas (1/2 cup cooked)', 134, 'legumes'),
('Lentils (1/2 cup cooked)', 115, 'legumes'),
('Pinto beans (1/2 cup cooked)', 122, 'legumes'),
('Edamame (1/2 cup shelled)', 94, 'legumes'),
('Green peas (1/2 cup)', 59, 'legumes'),
('Tofu, firm (3 oz)', 70, 'legumes'),
('Tofu, silken (3 oz)', 45, 'legumes'),
('Peanut butter (2 tbsp)', 191, 'legumes'),
('Almond butter (2 tbsp)', 196, 'legumes'),
('Black bean soup (1 cup)', 218, 'legumes'),
('Navy beans (1/2 cup cooked)', 127, 'legumes'),
('Soy milk (1 cup)', 80, 'legumes'),
('Tempeh (3 oz)', 160, 'legumes'),

-- ============================================================
-- SNACKS & SWEETS
-- ============================================================
('Lay''s Classic Chips (1 oz bag)', 160, 'snacks'),
('Doritos, Nacho Cheese (1 oz)', 150, 'snacks'),
('Pretzels (1 oz)', 108, 'snacks'),
('Popcorn, air-popped (1 cup)', 31, 'snacks'),
('Mixed nuts (1 oz)', 170, 'snacks'),
('Almonds (1 oz, ~23 nuts)', 164, 'snacks'),
('Cashews (1 oz)', 157, 'snacks'),
('Peanuts, dry roasted (1 oz)', 161, 'snacks'),
('Walnuts (1 oz)', 185, 'snacks'),
('Dark chocolate (1 oz)', 170, 'snacks'),
('Milk chocolate bar (1.5 oz)', 235, 'snacks'),
('Oreo cookies (3 cookies)', 160, 'snacks'),
('Graham crackers (2 full sheets)', 120, 'snacks'),
('Rice cake, plain (1 cake)', 35, 'snacks'),
('Trail mix (1/4 cup)', 173, 'snacks'),
('Sunflower seeds (1 oz)', 165, 'snacks'),
('Protein bar, average (1 bar)', 200, 'snacks'),
('Kind Bar (1 bar)', 200, 'snacks'),
('Clif Bar (1 bar)', 250, 'snacks'),
('Cheez-It Crackers (1 oz / 27 crackers)', 150, 'snacks'),
('Goldfish Snack Crackers (55 pieces)', 140, 'snacks'),
('Pringles, original (16 chips)', 150, 'snacks'),
('M&Ms (1 oz / small pack)', 140, 'snacks'),
('Snickers bar (1 standard)', 280, 'snacks'),
('Kit Kat (1 standard bar)', 218, 'snacks'),
('Reese''s Peanut Butter Cups (2-pack)', 210, 'snacks'),
('Twix Bar (1 standard)', 250, 'snacks'),
('Fruit Roll-Up (1 roll)', 50, 'snacks'),
('Applesauce, unsweetened (1/2 cup)', 50, 'snacks'),
('String cheese (1 stick)', 80, 'snacks'),
('Hard-boiled egg (1 large)', 78, 'snacks'),

-- ============================================================
-- BEVERAGES
-- ============================================================
('Water (8 oz)', 0, 'beverages'),
('Orange juice (1 cup)', 112, 'beverages'),
('Apple juice (1 cup)', 114, 'beverages'),
('Coca-Cola (12 oz can)', 140, 'beverages'),
('Pepsi (12 oz can)', 150, 'beverages'),
('Sprite (12 oz can)', 140, 'beverages'),
('Diet Coke (12 oz can)', 0, 'beverages'),
('Gatorade Thirst Quencher (12 oz)', 80, 'beverages'),
('Red Bull (8.4 oz can)', 110, 'beverages'),
('Monster Energy (16 oz can)', 210, 'beverages'),
('Coffee, black (8 oz)', 2, 'beverages'),
('Coffee with cream and sugar (8 oz)', 55, 'beverages'),
('Green tea (8 oz)', 0, 'beverages'),
('Iced tea, sweetened (8 oz)', 90, 'beverages'),
('Iced tea, unsweetened (8 oz)', 2, 'beverages'),
('Smoothie, fruit blend (12 oz)', 200, 'beverages'),
('Beer, regular lager (12 oz)', 153, 'beverages'),
('Beer, light (12 oz)', 110, 'beverages'),
('Wine, red (5 oz glass)', 125, 'beverages'),
('Wine, white (5 oz glass)', 121, 'beverages'),
('Vodka (1.5 oz shot)', 97, 'beverages'),
('Lemonade (8 oz)', 99, 'beverages'),
('Hot cocoa (8 oz with mix)', 218, 'beverages'),
('Protein shake, chocolate (12 oz)', 200, 'beverages'),

-- ============================================================
-- CONDIMENTS & EXTRAS
-- ============================================================
('Ketchup (1 tbsp)', 17, 'condiments'),
('Mustard, yellow (1 tbsp)', 9, 'condiments'),
('Mayonnaise (1 tbsp)', 94, 'condiments'),
('Ranch dressing (2 tbsp)', 145, 'condiments'),
('Italian dressing (2 tbsp)', 71, 'condiments'),
('Caesar dressing (2 tbsp)', 163, 'condiments'),
('Thousand Island dressing (2 tbsp)', 114, 'condiments'),
('Balsamic vinaigrette (2 tbsp)', 90, 'condiments'),
('Salsa (2 tbsp)', 10, 'condiments'),
('Guacamole (2 tbsp)', 50, 'condiments'),
('Olive oil (1 tbsp)', 119, 'condiments'),
('Honey (1 tbsp)', 64, 'condiments'),
('Maple syrup (1 tbsp)', 52, 'condiments'),
('Soy sauce (1 tbsp)', 11, 'condiments'),
('Hot sauce (1 tsp)', 0, 'condiments'),
('BBQ sauce (2 tbsp)', 70, 'condiments'),
('Sriracha (1 tsp)', 5, 'condiments'),
('Hummus (2 tbsp)', 60, 'condiments'),
('Pesto (2 tbsp)', 160, 'condiments'),
('Tomato pasta sauce (1/2 cup)', 70, 'condiments'),

-- ============================================================
-- FAST FOOD — McDONALD'S
-- ============================================================
('McDonald''s Big Mac', 550, 'fast-food'),
('McDonald''s Quarter Pounder with Cheese', 520, 'fast-food'),
('McDonald''s McDouble', 400, 'fast-food'),
('McDonald''s Cheeseburger', 300, 'fast-food'),
('McDonald''s Hamburger', 250, 'fast-food'),
('McDonald''s McChicken Sandwich', 400, 'fast-food'),
('McDonald''s Chicken McNuggets (6 pc)', 270, 'fast-food'),
('McDonald''s Chicken McNuggets (10 pc)', 450, 'fast-food'),
('McDonald''s Chicken McNuggets (20 pc)', 890, 'fast-food'),
('McDonald''s French Fries (small)', 230, 'fast-food'),
('McDonald''s French Fries (medium)', 320, 'fast-food'),
('McDonald''s French Fries (large)', 490, 'fast-food'),
('McDonald''s Egg McMuffin', 310, 'fast-food'),
('McDonald''s Sausage McMuffin with Egg', 480, 'fast-food'),
('McDonald''s Hotcakes (3 plain)', 350, 'fast-food'),
('McDonald''s McFlurry with Oreo (regular)', 510, 'fast-food'),
('McDonald''s Soft Serve Cone (vanilla)', 200, 'fast-food'),
('McDonald''s Baked Apple Pie', 240, 'fast-food'),
('McDonald''s Hash Brown', 150, 'fast-food'),
('McDonald''s Filet-O-Fish', 390, 'fast-food'),
('McDonald''s Double Quarter Pounder with Cheese', 740, 'fast-food'),
('McDonald''s Crispy Chicken Sandwich', 470, 'fast-food'),
('McDonald''s McRib', 520, 'fast-food'),
('McDonald''s Sausage Biscuit with Egg', 520, 'fast-food'),
('McDonald''s Medium Fountain Drink (Coke)', 210, 'fast-food'),

-- ============================================================
-- FAST FOOD — BURGER KING
-- ============================================================
('Burger King Whopper', 660, 'fast-food'),
('Burger King Whopper Jr', 310, 'fast-food'),
('Burger King Double Whopper', 900, 'fast-food'),
('Burger King Cheeseburger', 300, 'fast-food'),
('Burger King Original Chicken Sandwich', 470, 'fast-food'),
('Burger King Spicy Crispy Chicken Sandwich', 520, 'fast-food'),
('Burger King Chicken Fries (9 pc)', 290, 'fast-food'),
('Burger King Onion Rings (medium)', 410, 'fast-food'),
('Burger King French Fries (medium)', 380, 'fast-food'),
('Burger King Impossible Whopper', 630, 'fast-food'),
('Burger King French Toast Sticks (5 pc)', 390, 'fast-food'),
('Burger King Mozzarella Sticks (4 pc)', 310, 'fast-food'),
('Burger King Chocolate Shake (medium)', 700, 'fast-food'),

-- ============================================================
-- FAST FOOD — WENDY'S
-- ============================================================
('Wendy''s Dave''s Single', 590, 'fast-food'),
('Wendy''s Dave''s Double', 840, 'fast-food'),
('Wendy''s Baconator', 950, 'fast-food'),
('Wendy''s Spicy Chicken Sandwich', 500, 'fast-food'),
('Wendy''s Classic Chicken Sandwich', 470, 'fast-food'),
('Wendy''s Chicken Nuggets (10 pc)', 430, 'fast-food'),
('Wendy''s Frosty, Chocolate (small)', 340, 'fast-food'),
('Wendy''s French Fries (medium)', 420, 'fast-food'),
('Wendy''s Baked Potato, plain', 260, 'fast-food'),
('Wendy''s Caesar Salad (no dressing)', 180, 'fast-food'),
('Wendy''s Chili (small)', 160, 'fast-food'),

-- ============================================================
-- FAST FOOD — CHICK-FIL-A
-- ============================================================
('Chick-fil-A Chicken Sandwich', 440, 'fast-food'),
('Chick-fil-A Deluxe Chicken Sandwich', 500, 'fast-food'),
('Chick-fil-A Spicy Deluxe Sandwich', 550, 'fast-food'),
('Chick-fil-A Nuggets (8 pc)', 250, 'fast-food'),
('Chick-fil-A Nuggets (12 pc)', 380, 'fast-food'),
('Chick-fil-A Grilled Chicken Sandwich', 320, 'fast-food'),
('Chick-fil-A Waffle Fries (medium)', 400, 'fast-food'),
('Chick-fil-A Mac & Cheese (medium)', 440, 'fast-food'),
('Chick-fil-A Frosted Lemonade (medium)', 330, 'fast-food'),
('Chick-fil-A Chicken Biscuit', 450, 'fast-food'),
('Chick-fil-A Cobb Salad (no dressing)', 500, 'fast-food'),

-- ============================================================
-- FAST FOOD — TACO BELL
-- ============================================================
('Taco Bell Crunchy Taco', 170, 'fast-food'),
('Taco Bell Soft Taco, Chicken', 180, 'fast-food'),
('Taco Bell Burrito Supreme, Chicken', 460, 'fast-food'),
('Taco Bell Bean Burrito', 380, 'fast-food'),
('Taco Bell Cheesy Gordita Crunch', 500, 'fast-food'),
('Taco Bell Nachos BellGrande', 740, 'fast-food'),
('Taco Bell Crunchwrap Supreme', 530, 'fast-food'),
('Taco Bell Chicken Quesadilla', 520, 'fast-food'),
('Taco Bell Mexican Pizza', 540, 'fast-food'),
('Taco Bell Nacho Cheese Doritos Locos Taco', 170, 'fast-food'),
('Taco Bell Cheesy Bean and Rice Burrito', 420, 'fast-food'),
('Taco Bell Freeze, Mountain Dew Baja Blast (medium)', 280, 'fast-food'),

-- ============================================================
-- FAST FOOD — SUBWAY
-- ============================================================
('Subway Turkey Breast (6 inch)', 280, 'fast-food'),
('Subway Italian BMT (6 inch)', 450, 'fast-food'),
('Subway Veggie Delite (6 inch)', 230, 'fast-food'),
('Subway Tuna (6 inch)', 480, 'fast-food'),
('Subway Chicken & Bacon Ranch Melt (6 inch)', 570, 'fast-food'),
('Subway Steak & Cheese (6 inch)', 380, 'fast-food'),
('Subway BLT (6 inch)', 360, 'fast-food'),
('Subway Meatball Marinara (6 inch)', 480, 'fast-food'),
('Subway Turkey Breast Footlong', 560, 'fast-food'),
('Subway Italian BMT Footlong', 900, 'fast-food'),
('Subway Chocolate Chip Cookie', 210, 'fast-food'),
('Subway Baked Lays Chips (1 bag)', 130, 'fast-food'),

-- ============================================================
-- FAST FOOD — CHIPOTLE
-- ============================================================
('Chipotle Chicken Burrito Bowl (rice, beans, salsa)', 845, 'fast-food'),
('Chipotle Chicken Burrito', 1045, 'fast-food'),
('Chipotle Steak Burrito Bowl', 890, 'fast-food'),
('Chipotle Veggie Bowl', 680, 'fast-food'),
('Chipotle Chips and Guacamole', 490, 'fast-food'),
('Chipotle Chicken Tacos (3)', 465, 'fast-food'),
('Chipotle Steak Tacos (3)', 480, 'fast-food'),
('Chipotle Carnitas Bowl', 800, 'fast-food'),
('Chipotle Sofritas Bowl', 745, 'fast-food'),
('Chipotle Cheese (side)', 110, 'fast-food'),
('Chipotle Sour Cream (side)', 120, 'fast-food'),

-- ============================================================
-- FAST FOOD — STARBUCKS
-- ============================================================
('Starbucks Caffe Latte, Grande (whole milk)', 190, 'fast-food'),
('Starbucks Cappuccino, Grande', 120, 'fast-food'),
('Starbucks Mocha Frappuccino, Grande', 370, 'fast-food'),
('Starbucks Cold Brew Coffee, Grande (black)', 5, 'fast-food'),
('Starbucks Pumpkin Spice Latte, Grande', 380, 'fast-food'),
('Starbucks Iced Caramel Macchiato, Grande', 250, 'fast-food'),
('Starbucks Vanilla Latte, Grande', 250, 'fast-food'),
('Starbucks Croissant', 230, 'fast-food'),
('Starbucks Banana Bread slice', 420, 'fast-food'),
('Starbucks Chocolate Croissant', 330, 'fast-food'),
('Starbucks Egg & Gouda Breakfast Sandwich', 350, 'fast-food'),
('Starbucks Caramel Ribbon Crunch Frappuccino, Grande', 470, 'fast-food'),
('Starbucks Matcha Latte, Grande (oat milk)', 240, 'fast-food'),

-- ============================================================
-- FAST FOOD — KFC
-- ============================================================
('KFC Original Recipe Chicken Breast', 390, 'fast-food'),
('KFC Original Recipe Chicken Drumstick', 130, 'fast-food'),
('KFC Original Recipe Chicken Thigh', 280, 'fast-food'),
('KFC Extra Crispy Chicken Breast', 510, 'fast-food'),
('KFC Popcorn Nuggets (large)', 490, 'fast-food'),
('KFC Mashed Potatoes with Gravy (individual)', 120, 'fast-food'),
('KFC Coleslaw (individual)', 150, 'fast-food'),
('KFC Biscuit (1)', 180, 'fast-food'),
('KFC Famous Bowl', 710, 'fast-food'),
('KFC Corn on the Cob (1 ear)', 70, 'fast-food'),
('KFC Mac & Cheese (individual)', 140, 'fast-food'),

-- ============================================================
-- FAST FOOD — PIZZA
-- ============================================================
('Domino''s Hand Tossed Cheese Pizza (1 slice, medium)', 290, 'fast-food'),
('Domino''s Hand Tossed Pepperoni Pizza (1 slice, medium)', 310, 'fast-food'),
('Domino''s Thin Crust Cheese Pizza (1 slice, medium)', 190, 'fast-food'),
('Domino''s Stuffed Cheesy Bread (2 pieces)', 370, 'fast-food'),
('Domino''s Chicken Wings (6 pc, plain)', 610, 'fast-food'),
('Pizza Hut Pepperoni Pizza, Hand-Tossed (1 slice, medium)', 300, 'fast-food'),
('Pizza Hut Cheese Pizza, Pan (1 slice, medium)', 290, 'fast-food'),
('Little Caesars Hot-N-Ready Cheese Pizza (1 slice)', 250, 'fast-food'),
('Frozen pizza, cheese (1 slice)', 249, 'fast-food'),

-- ============================================================
-- FAST FOOD — OTHER CHAINS
-- ============================================================
('Panera Bread Fuji Apple Chicken Salad (full)', 570, 'fast-food'),
('Panera Bread Broccoli Cheddar Soup (1 cup)', 290, 'fast-food'),
('Panera Bread Chocolate Chip Cookie', 440, 'fast-food'),
('Panera Bread Turkey Sandwich (half)', 370, 'fast-food'),
('Five Guys Cheeseburger', 840, 'fast-food'),
('Five Guys Little Cheeseburger', 550, 'fast-food'),
('Five Guys Regular Fries', 953, 'fast-food'),
('Shake Shack ShackBurger', 560, 'fast-food'),
('Shake Shack Crinkle Cut Fries (regular)', 470, 'fast-food'),
('Shake Shack Double ShackBurger', 790, 'fast-food'),
('In-N-Out Hamburger', 390, 'fast-food'),
('In-N-Out Cheeseburger', 480, 'fast-food'),
('In-N-Out Double-Double', 670, 'fast-food'),
('In-N-Out French Fries', 400, 'fast-food'),
('Panda Express Orange Chicken (5.4 oz)', 380, 'fast-food'),
('Panda Express Fried Rice (1 serving)', 520, 'fast-food'),
('Panda Express Chow Mein (1 serving)', 510, 'fast-food'),
('Dunkin Glazed Donut (1)', 270, 'fast-food'),
('Dunkin Bacon Egg and Cheese Croissant', 500, 'fast-food'),
('Dunkin Medium Iced Coffee with Cream', 80, 'fast-food'),
('IHOP Buttermilk Pancakes (3 plain)', 430, 'fast-food'),
('Olive Garden Spaghetti with Marinara (dinner)', 750, 'fast-food'),
('Olive Garden Breadstick (1)', 140, 'fast-food'),
('Applebee''s Classic Cheeseburger', 800, 'fast-food'),
('Buffalo Wild Wings Classic Wings (6 pc)', 430, 'fast-food'),
('Buffalo Wild Wings Boneless Wings (6 pc)', 540, 'fast-food'),
('Popeyes Chicken Sandwich (original)', 700, 'fast-food'),
('Popeyes Spicy Chicken Sandwich', 700, 'fast-food'),
('Popeyes Classic Chicken Breast (2 pc)', 420, 'fast-food'),
('Raising Cane''s Box Combo (3 tenders, fries, toast)', 1040, 'fast-food'),
('Culver''s ButterBurger with Cheese', 490, 'fast-food'),
('Wingstop Lemon Pepper Wings (6 pc)', 430, 'fast-food'),
('Sonic Cheeseburger', 580, 'fast-food'),
('Sonic Corn Dog (1)', 210, 'fast-food'),
('Jersey Mike''s Turkey Sub (regular)', 555, 'fast-food'),
('Jimmy John''s Turkey Tom (8 inch)', 499, 'fast-food'),

-- ============================================================
-- PREPARED / HOME MEALS
-- ============================================================
('Chicken Caesar salad (1 serving)', 470, 'prepared-foods'),
('Garden salad, no dressing (2 cups)', 20, 'prepared-foods'),
('Tomato soup (1 cup, canned)', 90, 'prepared-foods'),
('Chicken noodle soup (1 cup)', 62, 'prepared-foods'),
('Chili with beans (1 cup)', 287, 'prepared-foods'),
('Beef stew (1 cup)', 220, 'prepared-foods'),
('Macaroni and cheese (1 cup, boxed)', 327, 'prepared-foods'),
('Grilled cheese sandwich', 390, 'prepared-foods'),
('BLT sandwich', 400, 'prepared-foods'),
('Peanut butter and jelly sandwich', 390, 'prepared-foods'),
('Chicken burrito (homemade)', 530, 'prepared-foods'),
('Chicken stir fry with vegetables (1 cup)', 280, 'prepared-foods'),
('Fried rice with vegetables (1 cup)', 333, 'prepared-foods'),
('French toast (2 slices)', 330, 'prepared-foods'),
('Buttermilk pancakes with syrup (3 medium)', 520, 'prepared-foods'),
('Beef tacos (2 tacos)', 380, 'prepared-foods'),
('Cheese pizza, homemade (1 slice)', 272, 'prepared-foods'),
('Spaghetti with meat sauce (1.5 cups)', 590, 'prepared-foods'),
('Chicken stir fry (1 cup)', 300, 'prepared-foods'),
('Caesar salad, no dressing (2 cups)', 45, 'prepared-foods'),
('Greek salad (1 serving)', 185, 'prepared-foods'),
('Turkey club sandwich', 540, 'prepared-foods'),
('Egg salad sandwich', 390, 'prepared-foods'),
('Tuna salad sandwich', 460, 'prepared-foods'),
('Chicken quesadilla (1 whole)', 520, 'prepared-foods'),
('Veggie burger patty (1 patty)', 130, 'prepared-foods'),
('Cheeseburger (homemade)', 490, 'prepared-foods'),
('Beef nachos (1 serving)', 570, 'prepared-foods'),
('Sushi roll, California (6 pieces)', 250, 'prepared-foods'),
('Sushi roll, Spicy Tuna (6 pieces)', 290, 'prepared-foods'),
('Pad Thai with chicken (1 cup)', 400, 'prepared-foods'),
('Fried chicken breast (1 piece)', 360, 'prepared-foods'),
('Lasagna with meat (1 piece, 3x4 inches)', 377, 'prepared-foods'),
('Meatloaf (3 oz slice)', 294, 'prepared-foods'),
('Chicken soup with noodles, homemade (1.5 cups)', 180, 'prepared-foods'),
('Bean and cheese burrito', 420, 'prepared-foods'),
('Pepperoni pizza slice (1 slice, 8 in pie)', 300, 'prepared-foods'),
('Grilled salmon with vegetables', 320, 'prepared-foods'),
('Beef tacos (3 small)', 430, 'prepared-foods'),
('Buddha bowl with quinoa and chickpeas', 450, 'prepared-foods'),
('Avocado toast (1 slice sourdough)', 200, 'prepared-foods');

-- ============================================================
-- Verify import
-- ============================================================
SELECT COUNT(*) AS total_foods FROM foods;
SELECT category, COUNT(*) AS count FROM foods GROUP BY category ORDER BY count DESC;
